### ISSUE TITLE
Autoformat big integers

### ISSUE THREAD

**Issue by samphippen** [samphippen/rubyfmt#121]
Rubyfmt should automatically do convenience formatting on big integers:

```ruby
5
500
5000
50000000
```

should become

```ruby
5
500
5_000
50_000_000
```

**Comment by samphippen** [comment]
The code you want to update is here: https://github.com/samphippen/rubyfmt/blob/master/src/rubyfmt.rb#L719

**Comment by twe4ked** [comment]
Rubocop is probably a good starting place for this.

https://github.com/rubocop-hq/rubocop/blob/f7559c18dc8911c82585bc8bae7e4de03edc5a5e/lib/rubocop/cop/style/numeric_literals.rb

**Comment by mikker** [comment]
Of course, there are always exceptions eg. credit card numbers which would make more sense as `4111_1111_1111_1111`. Not necessarily something needing to be _fixed_ but wanted to mention.

**Comment by robotdana** [comment]
another exception is for example rails' schema.rb version which is YYYY_MM_DD_HHMMSS

I'd prefer it if rubyfmt passed through numbers with underscores unchanged if it can

**Comment by twe4ked** [comment]
#123 was closed with the following comment:

> I think that given that people like to put their underscores in all sorts of interesting places, we shouldn't do this. […]
