### ISSUE TITLE
Hi, is this thing on? :3

### ISSUE THREAD

**Issue by felix91gr** [samphippen/rubyfmt#149]
Hellu. I heard of this project of yours from The Yak Shave. Since now I'm working as dev support on a Rails project, I've been thinking of using a formatter for our Ruby code. 

However, the activity here seems to have stalled in the last 3 months and the Readme doesn't say if it is known to break some Ruby code. Should I keep tabs on the project? Should I use it?

Thanks.

**Comment by mikker** [comment]
There's a rewrite in progress, converting much of the code to Rust; see https://github.com/samphippen/rubyfmt/pull/147

I'm not the developer of rubyfmt but my understanding is that there's still some way to go. I've seen people mention the Ruby plugin for Prettier if you want a formatter ASAP 😊

**Comment by samphippen** [comment]
Hi,

I'm developing this in my spare time, and don't know when it'll be ready for general use. Please do keep an eye on #147
