### ISSUE TITLE
Broken formatting for DSL-y runtime type annotations

### ISSUE THREAD

**Issue by denisdefreyne** [samphippen/rubyfmt#206]
* Ruby version: 2.7.0p0
* Rubyfmt git sha: 9d65851d1ba5ab44889624cd7122a28d5f1e81e2

(Context: I watched your _Building rubyfmt_ talk and got excited to try out rubyfmt.)

## Input file

```ruby
        contract C::KeywordArgs[compiled_content_cache: C::Or[Nanoc::Core::CompiledContentCache, Nanoc::Core::TextualCompiledContentCache], item_reps: Nanoc::Core::ItemRepRepo] => C::Any
        def initialize(compiled_content_cache:, item_reps:)
```

## Rubyfmt's output

```ruby
        contract(
          C::KeywordArgs[          compiled_content_cache: C::Or[Nanoc::Core::CompiledContentCache, Nanoc::Core::TextualCompiledContentCache],
          item_reps: Nanoc::Core::ItemRepRepo
] => C::Any
        )
        def initialize(compiled_content_cache:, item_reps:)
```

## This breaks because

This is very DSL-y, I know… it uses runtime annotations to do typechecking.

* The spacing after `C::KeywordArgs[` shouldn’t be there.

* `item_reps: …` is indented the same as `C::KeyWordArgs[…`, despite being nested within the, uhh, square-bracket method call invocation.

* The `] => C::Any` bit is not indented at all.

This is using [Contracts.ruby](https://egonschiele.github.io/contracts.ruby/).

**Comment by reese** [comment]
This should be fixed by #343, on the current master this looks like the following:

```ruby
contract(
  C::KeywordArgs[
    compiled_content_cache: C::Or[Nanoc::Core::CompiledContentCache, Nanoc::Core::TextualCompiledContentCache],
    item_reps: Nanoc::Core::ItemRepRepo
  ] => C::Any
)
def initialize(compiled_content_cache:, item_reps:)
end
```
