### ISSUE TITLE
Editor RubyMine support

### ISSUE THREAD

**Issue by harsh183** [samphippen/rubyfmt#207]
I really liked the Brighton Ruby talk on this and want to get started but I looked around and couldn't find anything for running `rubyfmt` on RubyMine. I *can* periodically run it from command line on the entire directory and RubyMine will refresh it but that feels quite hacky.

I don't know the right place to put this so I'm sorry if I'm not following the right format for the issues.

**Comment by sholden** [comment]
I've gotten rubyfmt wired up by using the File Watcher plugin. Once you install the plugin, go to Tools -> File Watchers and add one that looks like this (assuming rubyfmt is in your path).

![image](https://user-images.githubusercontent.com/8165/90933920-3b32eb80-e3b5-11ea-9a38-120249d022a3.png)

It can be a little janky sometimes if it fights with the builtin formatting support, but it's what I've got so far. Hope it helps.

**Comment by harsh183** [comment]
That looks pretty neat! Anyway to add this to the Jetbrains plugin repository?

**Comment by sholden** [comment]
The File Watcher plugin is in the repository. This is just setting up a watcher using that plugin.

**Comment by harsh183** [comment]
Sweet. I think that's good enough then. Thanks!

**Comment by fables-tales** [comment]
@sholden @harsh183 could one of you send a PR to put some docs about this in the readme ?

**Comment by harsh183** [comment]
That will be for the main `README.md`?

**Comment by fables-tales** [comment]
yes please!
GitHub <notifications@github.com> wrote:
“That will be for the main README.md?”

**Comment by harsh183** [comment]
https://github.com/penelopezone/rubyfmt/pull/245 - sorry I forgot about this. Just put the image and two links and that should be helpful enough for anyone right now. Maybe the future can have an official plugin on the jetbrains store once `rubyfmt` is looking kinda done.
