### ISSUE TITLE
Error when formatting a heredoc passed as a hash value

### ISSUE THREAD

**Issue by wadetandy** [samphippen/rubyfmt#209]
* Ruby version: 2.6.3
* Rubyfmt git sha: 9d65851d1ba5ab44889624cd7122a28d5f1e81e2

## Input file

```ruby
hash = {
  msg: <<~EOD,
    heredoc msg
  EOD
  opts: {
    foo: 'bar'
  }
}
```

## Rubyfmt's output

``` ruby
hash = {
  msg: <<~EOD,
  opts: {
    foo: "bar"
  }
}
heredoc msg
EOD
```

## This breaks because

It pulls the remaining keys of the hash into the heredoc instead.

**Comment by coreyja** [comment]
I think I found another variation of this bug, so commenting instead of creating a new issue.

The same happens with multi-line method invocations

* Rubyfmt version: v0.4.0-Darwin

## Input file

```ruby
puts(
  1,
  2,
  <<~TXT,
    3
    4
  TXT
)
```

## Output file

```ruby
puts(
  1,
  2,
  <<~TXT
)
3
4
TXT
```

**Comment by fables-tales** [comment]
btw @phiggins I'm working on this one
