### ISSUE TITLE
Potential speed increase by leveraging RubyVM::AbstractSyntaxTree

### ISSUE THREAD

**Issue by jonknapp** [samphippen/rubyfmt#21]
First off, ❤️ this project (or at least the desired end result) and I heard about it on the Yak Shave podcast. Thanks a lot for both.

I'm working on a lightning talk on the MRI v2.6.0 [RubyVM::AbstractSyntaxTree](https://rubyreferences.github.io/rubychanges/2.6.html#rubyvmabstractsyntaxtree) addition and noticed a pretty large speed difference between `ripper` (which I guess creates s-expressions) and the new AST functionality. For a quick example, I ran it against your [rubyfmt.rb](https://github.com/samphippen/rubyfmt/blob/master/src/rubyfmt.rb) file because of it's size and found the AST parsing about 4 times faster.

```
require 'ripper'
contents = IO.read('rubyfmt.rb')
start_time = Time.new; RubyVM::AbstractSyntaxTree.parse(contents); p Time.new - start_time
=> 0.003515
start_time = Time.new; Ripper.sexp(contents); p Time.new - start_time
=> 0.013822
```

I only wanted to bring this up just in case it's helpful. This requires MRI v2.6.0+ so I don't think it's a valid global replacement for this type of lib, but it may be something to help with performance in specific Ruby versions in the long term.

That said, I'm not well versed in this area and the benefits of hooking into the `sexp` parsing process may outweigh the benefits of generating the AST then going back through it. Also, not sure of the differences between the s-expression output for a file vs the AST nodes.

Have a great weekend!

**Comment by jonknapp** [comment]
I'm not sure if there's anything with lazy evaluation going on in the AST version vs the ripper version. That could definitely lead to some misrepresented results. (sorry to spam; just thought about this)

**Comment by searls** [comment]
My understanding is that while 2.6 AST is super duper neato and we are all
huge fans and ripper has lots of problems, the goal with rubyfmt is to be
able to format even quite old versions of Ruby with the same Ruby
interpreter as whatever is being used at test/runtime. So far now, that
means Ripper.

Someday, though!

**Comment by samphippen** [comment]
My feeling on this is that the ruby 2.6 stuff might be an eventual target for performance, but right now ripper is the way to go. Thanks for giving the heads up! I’ll close this for now but be sure to ping you if we start down that route.
