### ISSUE TITLE
"Rubyfmt failed to correctly deserialize a tree from ripper" in persistent-💎 gem

### ISSUE THREAD

**Issue by ivoanjo** [samphippen/rubyfmt#220]
Hey there! Thanks for working on `rubyfmt`, I'm really looking forward to it :)

I've tried with one of my gems, and ran into an issue. The file is identified below.

Let me know if I can provide any more info. And again, big thanks!

* Ruby version: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]`
* Rubyfmt git sha: https://github.com/penelopezone/rubyfmt/releases/tag/v0.3.1

## Input file

<https://gitlab.com/ivoanjo/persistent-dmnd/-/raw/master/lib/persistent_dmnd/jruby_9_2_set_workaround.rb>

## Rubyfmt's output

(None)

## This breaks because

(Fails)

**Comment by phiggins** [comment]
Hi,

I just tried this with the trunk version of rubyfmt and get no error formatting that file, so I'm closing this issue.

Thanks for the report!
