### ISSUE TITLE
"Rubyfmt failed to correctly deserialize a tree from ripper" in concurrent-ruby gem

### ISSUE THREAD

**Issue by ivoanjo** [samphippen/rubyfmt#221]
Hello again! After [my previous issue report](https://github.com/penelopezone/rubyfmt/issues/220) I decided to try `rubyfmt` with a few other Ruby gems that I had checked out locally.

`rubyfmt` fails to process multiple files from `concurrent-ruby`.

* Ruby version: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]`
* Rubyfmt git sha: https://github.com/penelopezone/rubyfmt/releases/tag/v0.3.1

## Input file

All of these fail:

* file was: docs-source/actor/messaging.in.rb
* file was: docs-source/actor/messaging.out.rb
* file was: examples/a-tour-of-go-channels/buffered-channels.rb
* file was: examples/a-tour-of-go-channels/channels.rb
* file was: examples/a-tour-of-go-channels/equivalent-binary-trees.rb
* file was: examples/a-tour-of-go-channels/select.rb
* file was: examples/go-by-example-channels/channel-directions.rb
* file was: examples/go-by-example-channels/channel-synchronization.rb
* file was: examples/go-by-example-channels/closing-channels.rb
* file was: examples/go-by-example-channels/rate-limiting.rb
* file was: examples/go-by-example-channels/timers.rb
* file was: examples/go-by-example-channels/worker-pools.rb
* file was: lib/concurrent-ruby/concurrent/collection/map/atomic_reference_map_backend.rb
* file was: lib/concurrent-ruby/concurrent/thread_safe/util/striped64.rb
* file was: spec/concurrent/atomic/count_down_latch_spec.rb
* file was: spec/concurrent/atomic/cyclic_barrier_spec.rb
* file was: spec/concurrent/atomic/event_spec.rb
* file was: spec/concurrent/mvar_spec.rb
* file was: tmp/x86_64-linux/stage/lib/concurrent/atomic_reference/direct_update.rb

Link to concurrent-ruby repository: https://github.com/ruby-concurrency/concurrent-ruby

## Rubyfmt's output

(None)

## This breaks because

Does not work ;)

**Comment by phiggins** [comment]
With #280, #281, #283, and #285 merged I'm able to successfully run rubyfmt on concurrent-ruby. Thanks for the report!

**Comment by fables-tales** [comment]
@phiggins this is amazing TY so much <3

do the tests pass after you format concurrent-ruby? If so what do you think about adding it to the stress test suite?

**Comment by phiggins** [comment]
> do the tests pass after you format concurrent-ruby? If so what do you think about adding it to the stress test suite?

Good idea, I can take a look at this soon.

**Comment by phiggins** [comment]
Unfortunately, the tests do not work after having rubyfmt run on the repo. 

I get this error:

```
pete@hexagon:~/projects/concurrent-ruby$ bundle exec rake spec
YARD is not installed, skipping documentation task definitions: cannot load such file -- yard
/home/pete/.asdf/installs/ruby/2.7.2/bin/ruby -I/home/pete/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib:/home/pete/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-support-3.10.2/lib /home/pete/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading spec_helper.
Failure/Error: require "concurrent/collection/lock_free_stack"

SyntaxError:
  /home/pete/projects/concurrent-ruby/lib/concurrent-ruby/concurrent/collection/lock_free_stack.rb:56: circular argument reference - head
# ./lib/concurrent-ruby/concurrent/promises.rb:4:in `require'
# ./lib/concurrent-ruby/concurrent/promises.rb:4:in `<top (required)>'
# ./lib/concurrent-ruby/concurrent.rb:34:in `require'
# ./lib/concurrent-ruby/concurrent.rb:34:in `<top (required)>'
# ./spec/spec_helper.rb:35:in `require'
# ./spec/spec_helper.rb:35:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00003 seconds (files took 0.20435 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00003 seconds (files took 0.20435 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples


/home/pete/.asdf/installs/ruby/2.7.2/bin/ruby -I/home/pete/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib:/home/pete/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-support-3.10.2/lib /home/pete/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

Looking at the diff of `lib/concurrent-ruby/concurrent/collection/lock_free_stack.rb` file, it's fairly easy to see why it's broken:

```
     # @param [Node] head
     # @return [true, false]
-    def empty?(head = head())
-      head.equal? EMPTY
+    def empty?(head = head)
+      head.equal?(EMPTY)
     end
```

rubyfmt is changing the call to `head()` to `head`, which is also the name of the variable the return value is assigned to. This is definitely a bug but I'm not sure how to handle this one.

**Comment by phiggins** [comment]
There is already a bug open for that, btw #130

**Comment by phiggins** [comment]
I did a little investigation and it seems like solving this is going to be hard, possibly requiring keeping track of locals in the scope or something. I was hoping that like #281, ripper might provide some additional hints that things are a little different in cases like this, but that does not appear to be the case:

```
pete@hexagon:~/projects/rubyfmt$ cat example.rb
def foo
  :foo
end

def bar
  :bar
end

foo = foo()
baz = bar()
qux = qux()
pete@hexagon:~/projects/rubyfmt$ cat example.rb | ruby -I. -rripper -rpp -e "pp Ripper.sexp(ARGF.read)"
[:program,
 [[:def,
   [:@ident, "foo", [1, 4]],
   [:params, nil, nil, nil, nil, nil, nil, nil],
   [:bodystmt,
    [[:symbol_literal, [:symbol, [:@ident, "foo", [2, 3]]]]],
    nil,
    nil,
    nil]],
  [:def,
   [:@ident, "bar", [5, 4]],
   [:params, nil, nil, nil, nil, nil, nil, nil],
   [:bodystmt,
    [[:symbol_literal, [:symbol, [:@ident, "bar", [6, 3]]]]],
    nil,
    nil,
    nil]],
  [:assign,
   [:var_field, [:@ident, "foo", [9, 0]]],
   [:method_add_arg, [:fcall, [:@ident, "foo", [9, 6]]], [:arg_paren, nil]]],
  [:assign,
   [:var_field, [:@ident, "baz", [10, 0]]],
   [:method_add_arg, [:fcall, [:@ident, "bar", [10, 6]]], [:arg_paren, nil]]],
  [:assign,
   [:var_field, [:@ident, "qux", [11, 0]]],
   [:method_add_arg, [:fcall, [:@ident, "qux", [11, 6]]], [:arg_paren, nil]]]]]
```

**Comment by fables-tales** [comment]
yeah ok, I know how to fix this and it's going to be UGLY

**Comment by phiggins** [comment]
lmao I look forward to seeing the PR then! Let me know if I can help somehow.
