### ISSUE TITLE
Dropping trailing comments

### ISSUE THREAD

**Issue by tekin** [samphippen/rubyfmt#223]
* Ruby version: 2.6.2
* Rubyfmt git sha: 1014a28

## Input file

- https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/app/models/maths_and_physics/dqt_record.rb
- https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/db/migrate/20190613133709_create_delayed_jobs.rb

## This breaks because

- Comments at https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/app/models/maths_and_physics/dqt_record.rb#L26-L30 are dropped
- Comments at https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/db/migrate/20190613133709_create_delayed_jobs.rb#L3-L13 are dropped

There are other examples of dropped trailing comments in this project, but mostly the same shape as the above two.

**Comment by fables-tales** [comment]
this should be fixed now!

**Comment by tekin** [comment]
🎉
