### ISSUE TITLE
`%w{...]...}` is wrongly formatted to `%w[...]...]`

### ISSUE THREAD

**Issue by mame** [samphippen/rubyfmt#225]
* Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
* Rubyfmt git sha: 3f3653ccc6210a37eab2954ad534c901d63604a4

## Input file

```ruby
%w{...]...}
```

## Rubyfmt's output

```
%w[...]...]
```

## This breaks because

The delimiters of `%w{}` is changed to brackets, and the contents include a closed bracket which unintentionally terminates the `%w` literal. I have no good idea how to fix, though.

**Comment by robotdana** [comment]
hi @penelopezone i'd like to look into this one if it's ok?
