### ISSUE TITLE
Have the test suite run with `cargo test`

### ISSUE THREAD

**Issue by sgrif** [samphippen/rubyfmt#234]
By having a bunch of custom shell scripts to run the test suite, we make the test suite harder to find, and also increase the barrier to entry for new contributors. I don't see anything about the suite that can't be done in Rust. We should seriously consider moving this into Rust, either by manually writing the boilerplate "check this file" when a new example is added, or by generating it with a proc macro. https://github.com/diesel-rs/diesel/blob/master/diesel_cli/tests/print_schema.rs is an example of a similar "run the binary associated with this crate on this input and diff stdout from this expected value" type of suite

**Comment by fables-tales** [comment]
I think I prefer to write a contributing.md and better improving the discoverability of these things. I agree it's hard to discover right now. I don't think rewriting it all in Rust provides that much leverage vs just documenting it well. This is for sure an artefact of Rubyfmt being a solo project for so long

**Comment by fables-tales** [comment]
added a contributing guide
