### ISSUE TITLE
all end of file comments are dropped inluding __END__ content

### ISSUE THREAD

**Issue by copiousfreetime** [samphippen/rubyfmt#239]
* Ruby 2.6.1, 2.7.1:
* Rubyfmt git sha: da5c3631779121f5281726c093f0548e00cf8034

## Input file

```ruby
#!/usr/bin/env ruby
#
# These are some leading comments before the code

puts "some code"
DATA.each do |line|
  puts line
end

#
# These are some trailing comments after the code
#

__END__
This is data
for the program
to output
```

## Rubyfmt's output

```ruby
#!/usr/bin/env ruby
#
# These are some leading comments before the code

puts("some code")

DATA.each do |line|
  puts(line)
end
```

## This breaks because

The trailing comments and the `__END__` section should exist in the output.

**Comment by copiousfreetime** [comment]
good chance I'll poke around on this in the next week. Not sure if this may be the same problem as  #188 #199 #223

**Comment by fables-tales** [comment]
I'm working on comments right now! You can sit back and relax and expect a fix shortly

**Comment by fables-tales** [comment]
@copiousfreetime I'm not going to fix `__END__` and then more stuff, because uh, that's hard. If you send a patch I will happily merge it. The end of file comments before the end I have a fix coming for momentarily.
