### ISSUE TITLE
Fails to parse `alias :"old_str_into_symbol" :"str_into_symbol"`

### ISSUE THREAD

**Issue by mikker** [samphippen/rubyfmt#248]
* Ruby version: 2.7.1
* Rubyfmt git sha: 0fd3fbbf7a4e8a52363dad99a48cec2c3d5d7a3a

## Input file

```ruby
alias :"old" :"new"
```

## Rubyfmt's output

_Failed to parse tree_

**Comment by fables-tales** [comment]
you should be able to fix this by modifying the alias node in `librubyfmt/src/ripper_tree_types.rs` if you're feeling ambitious, otherwise I'll get to it when I can
