### ISSUE TITLE
Breaks on strings with non-breaking spaces

### ISSUE THREAD

**Issue by localhostdotdev** [samphippen/rubyfmt#25]
* Ruby version: `ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin14]`
* Rubyfmt git sha: 83e6fbe4efc120e6d048c8cb17526f9dd3d30794

## Input file

```ruby
"<200b>"
```

(this is what I see in vim, you need to have the actual non breaking space character there)

## Rubyfmt's output

```
Traceback (most recent call last):
	3: from ../clones/rubyfmt/src/rubyfmt.rb:2185:in `<main>'
	2: from ../clones/rubyfmt/src/rubyfmt.rb:2173:in `main'
	1: from ../clones/rubyfmt/src/rubyfmt.rb:2173:in `parse'
../clones/rubyfmt/src/rubyfmt.rb:2159:in `on_string_literal': what even is this string type (RuntimeError)
```

## This breaks because

Should not crash.

**Comment by samphippen** [comment]
@localhostdotdev could you send over the output of `puts "<200b>".bytes` and `puts "<200b>".encoding`. I'm not exactly sure what vim is representing to the interpreter! Thanks.

**Comment by localhostdotdev** [comment]
`.bytes => [226, 128, 139]` (e.g. U+200B), `.encoding -> #<Encoding:UTF-8>`.

Nice you fixed all those other issues! I have also a bunch of weird formatting issues I will add, but not any more crashes on this project.
