### ISSUE TITLE
Slim embedded engines unsupported

### ISSUE THREAD

**Issue by dennyluan** [samphippen/rubyfmt#257]
If you have a slim file with a block at the top, rubyfmt eats the entire file.

* Ruby version: 2.7.1
* Rubyfmt git sha: 364d7fd0ef4285d42612bf32b360692c99a30f3f

## Input file
in a file.html.slim
```ruby
ruby:
  @this_should_be_ruby = "world"

h1 hello #{@this_should_be_ruby}! 
```

## Rubyfmt's output

```
ruby
```

## This breaks because

It looks like it also breaks with e.g. `javascript:` there too (https://rdoc.info/gems/slim/frames#embedded-engines-markdown).

**Comment by phiggins** [comment]
rubyfmt works on files of ruby code, not ruby code embedded in other formats. If the ruby interpreter can't read your file without additional support, rubyfmt won't be able to either. It's possible this could change in the future but it's not likely to happen anytime soon.
