### ISSUE TITLE
Reenable macos build in CI

### ISSUE THREAD

**Issue by phiggins** [samphippen/rubyfmt#276]
I disabled the macos build in CI in #269. It is failing with this error message:

```
   configure: error: cannot find required auxiliary files: config.guess config.sub
```

The full logs are here: https://github.com/penelopezone/rubyfmt/runs/2310759634

This is the same error that Ruby's own CI started throwing when it upgraded to autotools 2.70+: https://redmine.ruby-lang.org/issues/17723

Fixing this will likely involve some combination of waiting for that fix for ruby's build process to be backported to a 2.x branch, updating the version of ruby embedded in this project, and/or tweaking the github actions config to workaround the broken bits.

**Comment by fables-tales** [comment]
can you try the `autoreconf -i` trick mentioned in that thread?

**Comment by phiggins** [comment]
I did try that, I got a different error message. I think this is it but I can start a new PR to repro: https://github.com/penelopezone/rubyfmt/runs/2311550332?check_suite_focus=true#step:11:1086

**Comment by phiggins** [comment]
The current status of this:

* I opened #277 to see if changing `autoconf` to `autoreconf -i` would fix things as indicated in that ruby issue, and it didn't. It's currently failing with this error message:

```
  /Users/runner/work/rubyfmt/rubyfmt/librubyfmt/ruby_checkout/ruby-2.6.6//configure: line 4103: syntax error near unexpected token `fi'
  /Users/runner/work/rubyfmt/rubyfmt/librubyfmt/ruby_checkout/ruby-2.6.6//configure: line 4103: `fi ;; #('
```
* I'll keep that branch open to investigate potential solutions. If I can figure out a non-grossly hacky solution that makes it go green I'll merge it.
* I poked around to see if anyone else was having this problem and didn't, but I also couldn't find any references to anyone building Ruby 2.6.x with autoconf 2.71 either. For instance, ruby-build did the `autoreconf -i` change but it's not clear to me that it rebuilds all the rubies in their CI: https://github.com/rbenv/ruby-build/pull/1743

Things to investigate:

* Homebrew does not usually support installing multiple versions, but in this case it does have an older version of autoconf, 2.31, available (https://formulae.brew.sh/formula/autoconf). Pinning to an old version is not a great longterm solution but is better than the current state of a disabled mac build. I'll need to try installing the older version and getting the build system to use it, but I'm only familiar with the basics of homebrew and am not sure how easy it will be to debug this via CI.
* I have minimal exposure to github actions, so I'm not sure what kind of debugging capabilities it has. Ideally I could ssh in and manually poke at it but failing that there might be more debugging info to be gleaned from it.
* I don't have a mac to test on, so I can't tell if this is just broken for anyone trying to build on a mac with the newest autoconf. It might be helpful to determine if this problem is specific to github actions vs macs generally, or if the problem is building rubyfmt vs building ruby 2.6.x directly.

**Comment by phiggins** [comment]
* I got the macos build to use the older version of autoconf available in homebrew in this commit: https://github.com/penelopezone/rubyfmt/pull/277/commits/7de40be4ebd8b852896a4575dd0d7c52097f29f7

    However, it appears this version of autoconf must be too old, because that fails with a different error message:
```
Error: failed to run custom build command for `rubyfmt v0.1.0 (/Users/runner/work/rubyfmt/rubyfmt/librubyfmt)`
Caused by:
  process didn't exit successfully: `/Users/runner/work/rubyfmt/rubyfmt/target/debug/build/rubyfmt-db9cddb593a0b015/build-script-build` (exit code: 101)
  --- stderr
  autoconf: configure.in: No such file or directory
  thread 'main' panicked at 'failed subcommand', librubyfmt/build.rs:28:13
```

* I looked into whether I could ssh into the github actions instance, and while it appears possible I also saw mentions of it violating the TOS and I'd rather not get my account banned, so I won't be trying this.

Debugging this via CI is getting pretty frustrating and I'm not really sure what else to try here.

**Comment by phiggins** [comment]
I got #277 green by forcing homebrew to install autoconf 2.69, the previous version before they updated to 2.71. This doesn't feel great and it won't fix anyone using a mac who updates to 2.71, but this is the best I could come up with after staring at this for a few days.

**Comment by phiggins** [comment]
#277 is merged.

**Comment by phiggins** [comment]
* The backport issue on the ruby bug tracker: https://redmine.ruby-lang.org/issues/17775
* The github PR for the 2.6 branch: https://github.com/ruby/ruby/pull/4360
