### ISSUE TITLE
Trouble building on non-Intel Macs

### ISSUE THREAD

**Issue by mcmire** [samphippen/rubyfmt#288]
Hello! I have one of the new M1 Macs and tried to build rubyfmt following the steps laid out in the README, but was having trouble doing so. After much googling, I figured out a fix to get them to work:

1. Run `make all` once, watch it fail
2. Run `mv librubyfmt/ruby_checkout/ruby-2.6.6/.ext/include/-darwin20 librubyfmt/ruby_checkout/ruby-2.6.6/.ext/include/x86_64-darwin20`
3. Run `make all` again

What I think is happening here (although my knowledge of Autoconf, Automake, et al. is very limited) is that Ruby 2.6.6 (or at least the configure script it comes bundled with) is not able to detect arm64 CPUs properly and therefore the include path ends up being `-darwin20` instead of `arm64-darwin20` (or perhaps it would end up being `aarch64-darwin20`, I'm not sure). I am happy to try and fix this, but if this is one of those things that is not possible to fix due to using an older version of Ruby, then that's fine too! You can feel free to close this issue. Mostly I just wanted to bring this to y'all's attention.

**Comment by fables-tales** [comment]
I don't have a M1 mac so I don't know how to test this, but you likely need to update `librubyfmt/build.rs`. If you can make it work I will accept a patch

**Comment by reese** [comment]
#343 should include a fix for M1 macs (8b19d752fa382c86869ad03aa2b406f6a617a813), if that particular commit doesn't fix the build for your machine the fix is probably somemthing similar to that commit.
