### ISSUE TITLE
Extra newline inserted with multiline string that starts with an empty string

### ISSUE THREAD

**Issue by coreyja** [samphippen/rubyfmt#297]
* Ruby version: 2.7.2
* Rubyfmt git sha: 0.6.7

## Input file

```ruby
# Breaks
foo(
  "" \
  "a" \
  "b" \
  "c"
)

# Works Fine
foo("" \
  "a" \
  "b" \
  "c")

# Breaks
"" \
  "a" \
  "b" \
  "c"

# Breaks
[
  "" \
  "a" \
  "b" \
  "c",
]

# Works Fine
"a" \
  "a" \
  "b" \
  "c" 
```

## Rubyfmt's output

```ruby
# Breaks
foo(
  "" \

    "a" \
    "b" \
    "c"
)

# Works Fine
foo(
  "" \
    "a" \
    "b" \
    "c"
)
"" \

  # Breaks
  "a" \
  "b" \
  "c"

# Breaks
[
  "" \

    "a" \
    "b" \
    "c"
]

# Works Fine
"a" \
  "a" \
  "b" \
  "c"
```

## This breaks because

There is an extra new line inserted after `"" \`. Which causes it to no longer be valid Ruby code.

This seems to ONLY happen when the first string is an empty string. A non empty first string does not have the same behavior. [So removing the first empty string is likely the solution for the code base this came from]

There ARE situations where this does not seem to break, such as when it's used in a function call without extra new lines [The second example]

Where it places the comments makes it seem like it is treating `"" \` as a different expression than the second half, instead of a single expression

**Comment by reese** [comment]
This is fixed in #343, the output on master is now the following:

```ruby
# Breaks
foo(
  "" \
    "a" \
    "b" \
    "c"
)

# Works Fine
foo(
  "" \
    "a" \
    "b" \
    "c"
)

# Breaks
"" \
  "a" \
  "b" \
  "c"

# Breaks
[
  "" \
    "a" \
    "b" \
    "c"
]

# Works Fine
"a" \
  "a" \
  "b" \
  "c"
```
