### ISSUE TITLE
`super` in `define_method` breaks in certain situations

### ISSUE THREAD

**Issue by coreyja** [samphippen/rubyfmt#298]
* Ruby version: 2.7.7
* Rubyfmt version: 0.6.7

## Input file

```ruby
class A
  def foo
    :test
  end
end

class B < A
  define_method(:foo) do
    super().to_s if super()
  end
end

B.new.foo
```

## Rubyfmt's output

```ruby
class A
  def foo
    :test
  end
end

class B < A
  define_method(:foo) do
    super.to_s if super()
  end
end

B.new.foo
```

## This breaks because

One of the calls the `super()` in the define method is transformed to `super`. This breaks because `super` is _special_ and define method doesn't work with implicit argument passing, so it leads to the following syntax error

```
Traceback (most recent call last):
        1: from repro2.rb:13:in `<main>'
repro2.rb:9:in `block in <class:B>': implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly. (RuntimeError)
```

I _think_ this has something to do with chaining a method off the end of `super()`, because usages of `super()` alone, don't seem to trigger this bug

**Comment by reese** [comment]
This is fixed in #343 (see 923bb2d47a38c5df34f4e494a8a0736537fa0c3e for the specific fix)
