### ISSUE TITLE
Blocks ending with a comment moves comment outside block

### ISSUE THREAD

**Issue by mikker** [samphippen/rubyfmt#300]
Hey it's me again – comments ✨

* Ruby version: 2.7.3p183
* Rubyfmt git sha: `641534ce3730eaf060115a0c59b6bbbdd55ef4c0`

## Input file

```ruby
def m
  some_block do
    true
    # hello
  end
end
```

## Rubyfmt's output

```ruby
def m
  some_block do
    true
  end

  # hello
end
```

## This breaks because

You would've been done by now if it wasn't for comments 😅

**Comment by reese** [comment]
This is fixed in #343 (don't remember the specific commit because there are so many comment fixes in there 😅), but the output is now the following on master:

```ruby
def m
  some_block do
    true
    # hello
  end
end
```
