### ISSUE TITLE
Multi-line method call gets joined weirdly (or: Doesn't strip whitespace when joining multi-line method call)

### ISSUE THREAD

**Issue by mikker** [samphippen/rubyfmt#307]
* Ruby version: 2.7.3p183
* Rubyfmt git sha: `2983e2559cfe2810ec348965b8aa2c81729901a6`

## Input file

```ruby
def stub_server(path:, body: {})
  stub_request(
    :get,
    "https://example.com#{path}"
  ).to_return(body: body.to_json)
end
```

## Rubyfmt's output

```ruby
def stub_server(path:, body: {})
  stub_request(
    :get,
    "https://example.com#{path}"  ).to_return(body: body.to_json)
end
```

## This breaks because

Notice the non-stripped indentation whitespace after the string. I'd expect Rubyfmt to either strip that when joining the lines _or_ to keep the lines split.

Doesn't happen if I remove the trailing call to `.to_return(…)`.

**Comment by reese** [comment]
This is fixed in #343, the output on master is now the following (although it ends up being the same as the input in this case):

```ruby
def stub_server(path:, body: {})
  stub_request(
    :get,
    "https://example.com#{path}"
  ).to_return(body: body.to_json)
end
```
