### ISSUE TITLE
rubyfmt generates invalid ruby with rspec example all on one line

### ISSUE THREAD

**Issue by phiggins** [samphippen/rubyfmt#313]
rubyfmt generates invalid code for single line rspec examples like this one:
https://github.com/chef/chef/blob/master/spec/unit/util/editor_spec.rb#L25

rubyfmt strips the parens from the `it` call making the curly brace delimited block ambiguous:

```
$ cat example.rb
describe String do
  it("is a string") { expect(String.new).to be_kind_of(String) }
end
$ ./target/release/rubyfmt-main example.rb
describe String do
  it "is a string" { expect(String.new).to(be_kind_of(String)) }
end

**Comment by fables-tales** [comment]
the hard part of building a ruby autoformatter is all the RIDICULOUS parser rules for this language, but also this is a totally reasonable bug and we should fix it.
