### ISSUE TITLE
format `private def` nicely

### ISSUE THREAD

**Issue by fables-tales** [samphippen/rubyfmt#317]
```
private def foo
end
```

currently formats as

```
private(
  def foo
  end
)
```

we should format it the first way

**Comment by fables-tales** [comment]
@phiggins @sgrif would one of you two like to take this one?

**Comment by phiggins** [comment]
I can't build the project locally, so I'll likely be focusing any open source time on that for the near future.

**Comment by phiggins** [comment]
A method definition immediately preceded by `private` should get special formatting, or is this any method call on the same line as and immediately preceding a method definition gets special formatting? I don't know how common of a pattern this is (I'm not sure I've ever seen it in code), but you could do something like this as well:

```
pete@hexagon:~/projects/rubyfmt$ cat example.rb
class Foo
  private

  def foo_private
    :foo_private
  end

  public def foo_public
    :foo_public
  end
end

p Foo.new.foo_public
pete@hexagon:~/projects/rubyfmt$ ruby example.rb
:foo_public
```

**Comment by sgrif** [comment]
I'd actually argue against fixing this, or fixing it by changing the method definition to be the more standard form in Ruby. This is a super uncommon pattern (mostly only ever seen in code bases ported from Java in my experience), and I'm not sure it makes sense for a "one right unconfigurable way to format code" formatter to do this. Ideally we'd just group the method definitions up by visibility, but if there's code executing between the method definitions that could technically change the semantics

If we insist on special casing this, I think the rule for the special formatting should be "any call to a method named `public`, `private`, or `protected`, taking a single argument" (This would change `public(:foo)` to `public :foo` as well, which I think we should do if we're changing `public def foo; end` as well)

**Comment by fables-tales** [comment]
I think I'd actually like the rule to be: any method call where it has exactly one argument, which is a def or defs (e.g. def self.foo), we format it like this.

Because of e.g. the memoist thing: https://github.com/penelopezone/rubyfmt/blob/trunk/fixtures/small/memoist_actual.rb#L4

**Comment by dbalatero** [comment]
I have a WIP branch [here](https://github.com/penelopezone/rubyfmt/pull/266) that _almost_ works but there's a trailing newline after the method def that I can't get rid of, e.g.:

```ruby
class Foo
  private def bar
    42
  end

end
```
