### ISSUE TITLE
Add Gemfile `gem` method as special, un-parenthesised method

### ISSUE THREAD

**Issue by mikker** [samphippen/rubyfmt#330]
Similar to how RSpec's DSL methods stay un-parenthesised, I think adding parentheses to `gem` method calls in `Gemfile`s look weird. And perhaps weird enough to warrant a(nother) special case.

## Input file

```ruby
source "https://rubygems.org"
ruby "2.7.3"
gem "rspec"
```

## Rubyfmt's output

```ruby
source("https://rubygems.org")
ruby("2.7.3")
gem("rspec")
```

**Comment by fables-tales** [comment]
@reese can you take this one?

**Comment by reese** [comment]
Sure, I'll assign it to myself for now, should be able to take a look at this later this week 👍
