### ISSUE TITLE
Method call inside block with trailing comma and newline

### ISSUE THREAD

**Issue by jez** [samphippen/rubyfmt#334]
* Ruby version: 2.6.5
* Rubyfmt git sha: v0.7.6

## Input file

```ruby
foo {
  params(
  y: String,
  ).returns(String)}
```

## Rubyfmt's output

```
foo {
  params(
    y: String  ).returns(String)
}
```

## This breaks because

The `String  )` looks bad

maybe also other things should look different, not sure (maybe the `)` should be on a new line?)

**Comment by reese** [comment]
This is fixed after #343, the output now looks like this:

```ruby
foo {
  params(
    y: String
  ).returns(String)
}
```
