### ISSUE TITLE
Does it plan to support .erb files in the future?

### ISSUE THREAD

**Issue by Diogomartf** [samphippen/rubyfmt#342]
Does it plan to support `.erb` files in the future?

Might be doing this question on the wrong place, feel free to close it.

**Comment by reese** [comment]
This is a fine place to ask! That said, I don't think there are any plans for erb files. They have ruby _in_ them, but they can potentially hold ~anything, so the goals of formatting are unclear and may vary depending on what's it's a template _of_ (e.g. HTML, markdown, etc.), so I think it's out of scope for rubyfmt and would probably be better suited to a dedicated tool.

(Going to close this out, but feel free to follow up here -- happy to clarify anything there.)
