### ISSUE TITLE
rubyfmt removes parameters after a splat.

### ISSUE THREAD

**Issue by mori-nobuteru** [samphippen/rubyfmt#345]
* Ruby version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
* Rubyfmt git sha: 0.2.0 (installed via homebrew)

## Input file

```ruby
def some_method(a, *b, **c)
  puts(a, b.to_s, c)
end

b = ["1", "2", "3"]
some_method("a", *b, :key => 'value')
```

## Rubyfmt's output

```ruby
def some_method(a, *b, **c)
  puts(a, b.to_s, c)
end

b = ["1", "2", "3"]
some_method("a", *b)  # <-- Issue here
```

## This breaks because
rubyfmt removes the last parameter passed to some_method incorrectly.

**Comment by reese** [comment]
I'd probably recommend testing this on the current master branch -- `0.2.0` is several years old. I ran this example on the current master and this no longer reproduces. This is the output currently:

```ruby
def some_method(a, *b, **c)
  puts(a, b.to_s, c)
end

b = ["1", "2", "3"]
some_method("a", *b, :key => "value")
```
