### ISSUE TITLE
Breaks on regular expressions with random separators

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#35]
* Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
* Rubyfmt git sha: cbc2e0edd23af6abc63659bd654e5580c4521571

## Input file

```ruby
%r(foo)
```

## Rubyfmt's output

```
Traceback (most recent call last):
  7: from ../rubyfmt/src/rubyfmt.rb:2285:in `<main>'
  6: from ../rubyfmt/src/rubyfmt.rb:2282:in `main'
  5: from ../rubyfmt/src/rubyfmt.rb:2142:in `format_program'
  4: from ../rubyfmt/src/rubyfmt.rb:2142:in `each'
  3: from ../rubyfmt/src/rubyfmt.rb:2143:in `block in format_program'
  2: from ../rubyfmt/src/rubyfmt.rb:2136:in `format_expression'
  1: from ../rubyfmt/src/rubyfmt.rb:2110:in `block in format_expression'
../rubyfmt/src/rubyfmt.rb:1709:in `format_regexp_literal': got unknown regular expression (RuntimeError)
```

## This breaks because

Regular expressions can be separated by more or less any character. As I recall it, parentheses, brackets and braces must be paired, while any other character can be used if you use the same at the start and the end of the regex. E.g. `%r(foo)`, `%r{foo}`, `%r[foo]`, `%r_foo_`, `%r|foo|` are all equivalent.

**Comment by samphippen** [comment]
fixed by eab3bfa1962453277b63e28b5df3209f34dbfe29
