### ISSUE TITLE
VSCode integration with --header-opt-out 

### ISSUE THREAD

**Issue by matthewford** [samphippen/rubyfmt#354]
Hi, I would like to use the opt-out argument to aid the adoption on a complex project.

However, it looks like the VSCode extension does not support additional arguments. Would it be possible to make --header-opt-out a default setting?

**Comment by reese** [comment]
I think I'd be okay with making the header-opt-out functionality a default (other code formatters _also_ have something like this by default, e.g. `// prettier-ignore`), as long as we still had the reverse (like `--no-header-opt-out` or whatever). PRs would be welcome here!

**Comment by fables-tales** [comment]
@reese let's add a `~/.rubyfmtrc` and `$(pwd)/.rubyfmtrc` that passes flags in? I think the VS code extension runs rubyfmt from `$(pwd)` so that should work just fine?

we should not pass the opt out by default

**Comment by fables-tales** [comment]
oh and `XDG_CONFIG_HOME`

**Comment by reese** [comment]
I think an rc file would be fine, I guess my main concern there is just adding more complexity (e.g. is there a world where we need to support ENV variables when reading the rc file, we probably now need to handle how precedence works if the system file and pwd file conflict, etc.)

**Comment by fables-tales** [comment]
I buy that, maybe the right thing to do is instead have folks build a wrapper shell script that passes the flags they want?

**Comment by fables-tales** [comment]
i.e. `your/project/rubyfmt`

```
#!/bin/bash
rubyfmt --flags --you --care --about $*
```

**Comment by reese** [comment]
Yeah, the wrapper script is the way we did it (and still do it) for the Stripe rollout. I don't think it's a perfect end state, but I think it's good enough for most cases at the moment, especially since we have pretty few flags at the moment.

**Comment by fables-tales** [comment]
@matthewford does the suggestion of using a wrapper script meet your needs here?

**Comment by reese** [comment]
Just as another option for this particular case, I don't know if we ever documented it (although we should), but there's _some_ support for a `.rubyfmtignore` file where you could add globs/directories you haven't rolled out to yet, that could be a good option if you're using this for a rollout.

**Comment by fables-tales** [comment]
@reese oh, let's document that

**Comment by matthewford** [comment]
A wrapper works, rubyfmtignore would be really useful too
