### ISSUE TITLE
Add a version flag

### ISSUE THREAD

**Issue by matthewford** [samphippen/rubyfmt#364]
There isn't an easy what to check what version of rubyfmt you are currently running

Ideally you could run `rubyfmt --version` or `-v`

**Comment by reese** [comment]
Which version of `rubyfmt` are you running? The CLI already has this (both `--version` and `-V`, they're listed in the `--help` output as well), but I believe this was only added in `0.8.0` and won't be present in older versions.

**Comment by reese** [comment]
(Going to close this out, but happy to answer any follow-up here!)

**Comment by matthewford** [comment]
when I was building from homebrew I forgot to add the from source flag, can ignore
