### ISSUE TITLE
Running `rubyfmt` with no args hangs

### ISSUE THREAD

**Issue by dbalatero** [samphippen/rubyfmt#373]
If you run `rubyfmt`, it just hangs there and appears to be trapping `ctrl c` and not exiting:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/59429/203440271-06f47511-087c-41d9-8c15-d28a45589860.png">

My expectation was that it would print out help when no arguments are passed. If that's not desired behavior, fixing `ctrl c` would be great so exiting is possible without doing a `kill -9`. Thanks!

**Comment by reese** [comment]
Fixing this in #376 -- it doesn't fix the signal handling bits, but I'll leave that to be fixed as part of #322.
