### ISSUE TITLE
Make all build command fails on arm64 M1 Mac

### ISSUE THREAD

**Issue by jscharf** [samphippen/rubyfmt#374]
* CPU: arm64
* Ruby version: 2.7.3
* Rubyfmt git sha: `45ab75807696dcf06894697e08a89ceda098fdae`

## Problem

I've cloned the repository and I've run `make all` and I'm seeing an error (see below).

## Rubyfmt's output

```
bash -c "find target/release | grep -i 'librubyfmt-.*\.a' | xargs rm; exit 0"
cargo build --release
   Compiling serde v1.0.143
   Compiling rubyfmt v0.8.0-pre ([redacted]/rubyfmt/librubyfmt)
   Compiling clap v3.2.16
error: failed to run custom build command for `rubyfmt v0.8.0-pre ([redacted]/rubyfmt/librubyfmt)`

Caused by:
  process didn't exit successfully: `[redacted]/rubyfmt/target/release/build/rubyfmt-902e33afb7ade1b5/build-script-build` (exit status: 1)
  --- stderr
  Can't exec "aclocal": No such file or directory at /opt/homebrew/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
  autoreconf: error: aclocal failed with exit status: 2
  Error: "Command autoreconf --install failed with: exit status: 2"
warning: build failed, waiting for other jobs to finish...
make: *** [release] Error 101
```

## This breaks because

I was expecting the `make all` command get all the way through the end.

## Things I've tried

* Erase repository, redownload, rerun `make all`
* `brew reinstall autoreconf`
* `rm -rf target/release/` and rerun `make all`

**Comment by reese** [comment]
I don't know if this is an arm issue, this looks like an issue with your autoconf installation. If I remember from debugging someone else's setup, I think installing autoconf 2.69 (instead of 2.71) worked for them, might be worth giving that a try.

**Comment by jscharf** [comment]
Thank you!

First I installed the specific version of autoconf using
```
brew install autoconf@2.69
```
Then I tried to uninstall autoconf and got the following error

```
rubyfmt % brew uninstall autoconf               
Error: Refusing to uninstall /opt/homebrew/Cellar/autoconf/2.71
because it is required by rbenv and ruby-build, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies autoconf
```
Then I ran the following to uninstall the 2.71 version of autoconf
```
brew uninstall --ignore-dependencies autoconf
```
Then I ran `make all` again and got the following error
```
error: failed to run custom build command for `rubyfmt v0.8.0-pre ([redacted]/rubyfmt/librubyfmt)`

Caused by:
  process didn't exit successfully: `[redacted]/rubyfmt/target/release/build/rubyfmt-902e33afb7ade1b5/build-script-build` (exit status: 1)
  --- stderr
  Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Then I removed the repo and re-cloned, and reran `make all` and got the following error

```
   Compiling jemallocator v0.3.2
error: failed to run custom build command for `rubyfmt v0.8.0-pre ([redacted]/rubyfmt/librubyfmt)`

Caused by:
  process didn't exit successfully: `[redacted]/rubyfmt/target/release/build/rubyfmt-902e33afb7ade1b5/build-script-build` (exit status: 1)
  --- stdout
  Submodule path 'ruby_checkout': checked out '7b413c1db3e65909c6899e1d3be4d16c3e76149c'

  --- stderr
  Submodule 'librubyfmt/ruby_checkout' (https://github.com/ruby/ruby) registered for path 'ruby_checkout'
  Cloning into '[redacted]/rubyfmt/librubyfmt/ruby_checkout'...
  Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
make: *** [release] Error 101
```

**Comment by reese** [comment]
Do you have `make` installed? If not, `brew install automake` might fix this. We probably should have better error messages for this, because the build scripts don't currently do much in the way of error handling.

Also FWIW, you probably don't need to reclone the repo each time -- if you just do a `cargo clean`, that's probably good enough unless you think `git` is _really_ messed up.

**Comment by jscharf** [comment]
I checked for make and I did have it installed
```
rubyfmt % which make 
/usr/bin/make
```
Checked the version and it was 3.81
```
rubyfmt % make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

I ran `brew install automake` and based on the output, it looks like it installed `autoconf` 2.71 again
```
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

You have 17 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/manifests/2.71
Already downloaded: [redacted]/Library/Caches/Homebrew/downloads/057cde2b686872aeeff2e91dc36d037807d7342dd50929fbdfea8bcc572fbed0--autoconf-2.71.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:a3d366c98b0da7a0a4f352eef49af9d612ac7aea4ffe420d49ff12bd90007415
Already downloaded: [redacted]/Library/Caches/Homebrew/downloads/7613e266193af4c54b2933e9cd512ec386425ef0f959ca0a802af833cafb2474--autoconf--2.71.arm64_ventura.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/automake/manifests/1.16.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:f68481d06be7fa3f0a0881edb825a336e7f6548191c762d68bd817183b238f5a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:f68481d06be7fa3f0a0881edb825a336e7f6548191c762d68bd817183b238f5a?se=2022-11-25T22%3A35%3A00Z&sig=s
######################################################################## 100.0%
==> Installing dependencies for automake: autoconf
==> Installing automake dependency: autoconf
==> Pouring autoconf--2.71.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/autoconf/2.71: 71 files, 3.2MB
==> Installing automake
==> Pouring automake--1.16.5.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/automake/1.16.5: 131 files, 3.5MB
==> Running `brew cleanup automake`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```
And after running `brew list` I do have both versions installed now
```
rubyfmt % brew list            
==> Formulae
autoconf
autoconf@2.69
```

However after that I was able to get all the way through the `make all` command this time, thank you!

I will move on to the next step in the README of copying the target release onto my path somewhere.

**Comment by reese** [comment]
Are you just trying to install rubyfmt? If you want an easier way, you can `brew install rubyfmt` instead of having to manually copy a binary around (I've got a [PR](https://github.com/penelopezone/rubyfmt/pull/372) up to add this to the README)

**Comment by jscharf** [comment]
Yes I was trying to install it so that I could use. I didn't realize that it was available in homebrew but that makes sense. 

I was able to install it via homebrew and run it this morning, so I'm going to consider this issue resolved. 

Thank you for helping me with this on a Friday! 

PS. I have zero Rust experience but if you think adding one of those build error messages would be a good entry point for someone to learn some Rust and contribute to the project, let me know and I can look into opening a pull request.

**Comment by reese** [comment]
If you're interested in contributing, I think this is a pretty reasonable entrypoint. It's pretty standard error handling stuff on the Rust side, it's mostly just getting some context on the build commands for the Ruby VM to give better error messages that's the more complex part of this.

If you want to take a look, pretty much everything you'd need to look at is in [`librubyfmt/build.rs`](https://github.com/penelopezone/rubyfmt/blob/trunk/librubyfmt/build.rs). I'm also more than happy to give some pointers if you'd like!

**Comment by jscharf** [comment]
I'm looking at that file you linked now and it looks fairly reasonable. I can try to watch some Rust introduction videos to get more familiar with the syntax, but any pointers you can give would go a long way I'm sure!
