### ISSUE TITLE
Command calls in ArefFields fail to deserialize

### ISSUE THREAD

**Issue by jscharf** [samphippen/rubyfmt#380]
* Ruby version: 2.7.3
* Rubyfmt git sha: homebrew release, see version check below

```
% rubyfmt --version                                            
rubyfmt-main 0.8.0-pre
```
```
% brew list rubyfmt         
/opt/homebrew/Cellar/rubyfmt/0.8.0/.crates.toml
/opt/homebrew/Cellar/rubyfmt/0.8.0/.crates2.json
/opt/homebrew/Cellar/rubyfmt/0.8.0/bin/rubyfmt
/opt/homebrew/Cellar/rubyfmt/0.8.0/bin/rubyfmt-main
```

## Input file

I can't share my source code at the moment as it doesn't belong to me, but I could change the names of everything to generic names and just share the structure of it if that would help.

~Here is a general skeleton of what it looks like (the real file is around 60 lines long):~

Edit 2022-12-03: (Updated code sample)
Here is the real structure of the original source code with a bunch of names changed to anonymize:
```ruby
# frozen_string_literal: true

module Fruit
  module Peach
    class Distribution
      attr_reader :baskets

      def initialize(baskets:)
        @baskets = baskets
        @modifiers = {}
      end

      def prioritized_baskets
        modify_baskets
        prune_baskets
        set_primary_basket
        baskets
      end

      private

        attr_reader :modifiers

        def modify_baskets
          baskets.each do |basket|
            baskets.contents.each do |item|
              modifier = find_modifier(item) || build_modifier(item)
              modifier.modify(baskets, item)
            end
          end
        end

        def build_modifier(item)
          modifiers[hash_item item] = Modifier.new(
            required_quantity: item.unit.required_quantity
          )
        end

        def find_modifier(item)
          modifiers[hash_item item]
        end

        def prune_baskets
          baskets.reject!(&:empty?)
        end

        def set_primary_basket
          baskets.first.is_primary = true if baskets.present? && baskets.none?(&:is_primary)
        end

        def hash_item(item)
          shipment = item.unit.shipment
          product  = item.unit.product

          return product.hash unless shipment

          product.hash ^ shipment.hash
        end
    end
  end
end
```

I found https://github.com/fables-tales/rubyfmt/blob/trunk/RELEASE_README.md and tried running the debug binary like so
```
% rubyfmt-debug -i -- <path-to-my-file>.rb 
zsh: command not found: rubyfmt-debug
```
I also tried installing the separate binary from Homebrew like so
```
% brew install rubyfmt-debug
...
Warning: No available formula with the name "rubyfmt-debug". Did you mean rubyfmt?
```

## Rubyfmt's output

```
% rubyfmt -i -- ./<path-to-my-file>.rb 
Error! source: ./<path-to-my-file>.rb

!!! Ruby Tree Deserialization Error !!!

Rubyfmt failed to correctly deserialize a tree from ripper. This is a bug that needs to be reported.
File a bug report at https://github.com/penelopezone/rubyfmt/issues/new.
Ideally you would include the full source code of the program you ran rubyfmt with.
If you can't do that for some reason, the best thing you can do is rerun rubyfmt on this program 
with the debug binary with `2>log_file` on the end and then send us the log file that gets generated.
```

## This breaks because

`rubyfmt` should be able to execute against *.rb files without throwing a `Ruby Tree Deserialization Error`. 

### Question

How does one run the `rubyfmt-debug` binary - is it available from binary that is built from source, and not the binary that is installed via Homebrew?

**Comment by reese** [comment]
Yes, the debug binary is only available when building from source, brew doesn't ship debug binaries. I think we also package it in the [Github release](https://github.com/fables-tales/rubyfmt/releases/tag/v0.8.0) if you want to try that.

Are you sure that (1) the example you've provided still fails in the same way as your real example and that (2) this isn't fixed on the current master branch? The example you've provided here passes both on 0.8.0 and master as far as I can tell.

**Comment by jscharf** [comment]
Ok thanks good to know about the homebrew releases not shipping with debug binaries. 

I did briefly try the Github release just now but got a macOS system protection error:

>“rubyfmt-debug” can’t be opened because Apple cannot check it for malicious software.
>
>This software needs to be updated. Contact the developer for more information.

I can deal with that at a later date, but for now I was able to go back into the cloned repository, pull the latest code down, and execute the debug binary this way:

```zsh
% target/debug/rubyfmt-main -i -- <path-to-file> 2>log_file
```

(Had to change the file extension to .txt afterward so I could upload it)

I've attached that log file to this comment:
[log_file.txt](https://github.com/fables-tales/rubyfmt/files/10145675/log_file.txt)

The only thing I changed was the directory names and file names on the one line where it says `Error! source: <filepath>`

I will also update my sample to be more accurate as after thinking about it more today, the sample I provided is not that valuable as it's too far away from the real code. I will update the issue description with the real code structure and just anonymize it.

**Comment by jscharf** [comment]
I've just updated the code sample in the issue description to be much closer to the real source code. I tested rubyfmt with the latest changes from Github and got the same result so it should be repeatable now. Sorry for providing the low-value code sample originally.

**Comment by reese** [comment]
Thanks for updating, yeah the bit it fails on is `modifiers[hash_item item] = ...`. A minimal repro is 
```
foo[puts a] = ""
```
Will follow up on this later (or anyone else is welcome to take a look if you're interested!), but in the meantime this will work if you do `modifiers[hash_item(item)]` instead in all the places that happens.

**Comment by jscharf** [comment]
Thank you for fixing that so quickly! I was able to pull down the latest code and it ran on that file successfully 👍
