### ISSUE TITLE
Argument not expected

### ISSUE THREAD

**Issue by glaucocustodio** [samphippen/rubyfmt#388]
* Ruby version: 3.0.1
* Rubyfmt git sha: `rubyfmt-main 0.8.0-pre`

## Command
```bash
file app/models/user.rb
=> app/models/user.rb: Ruby script text, ASCII text

rubyfmt -i app/models/user.rb
```

## Rubyfmt's output

```bash
error: Found argument 'app/models/user.rb' which wasn't expected, or isn't valid in this context

USAGE:
    rubyfmt [OPTIONS] [-- <include-paths>...]

For more information try --help
```

## This breaks because

I don't know, I installed it with `brew install rubyfmt`, I am currently on arch `arm64`.

**Comment by reese** [comment]
While I think we should eventually get rid of the requirement for the `--`, it's currently necessary, and the `README` gives examples of passing files:
```
rubyfmt -i -- app/models/user.rb
```

**Comment by reese** [comment]
Going to close this out since it's documented both in the help text and the README, and there are thoughts on potentially changing this anyways, but if you have any other questions feel free to reopen or add more comments!

**Comment by glaucocustodio** [comment]
I am sorry, it didn't click for me when I saw `rubyfmt -i -- files or directories` on README, should we add an example like `rubyfmt -i -- my_file.rb` next to it to make it clearer?

Thank you so much for your work, it's nice to see the Ruby community having its own formatter 👍🏻

**Comment by reese** [comment]
The current version (0.8.1) actually now supports both! I do want to reformat the README more broadly though, because there's now quite a few more flags than there were when the README was originally written, so I think it's worth revisiting that whole section at some point.
