### ISSUE TITLE
 rubyfmt produces invalid ruby on wayward splats

### ISSUE THREAD

**Issue by maxjacobson** [samphippen/rubyfmt#392]
* Ruby version: 2.7.6
* Rubyfmt git sha: [v0.8.1](https://github.com/fables-tales/rubyfmt/releases/tag/v0.8.1)

## Input file

```ruby
a = 1
b = 2
c = 3
*nums = [a, b, c]

p nums
```

N.B. - I don't know why we have that asterisk there, or what it's meant to achieve, but it is valid ruby and is the only bug I noticed when running rubyfmt on our ~400k lines of Ruby at work 😲 

## Rubyfmt's output

```
a = 1
b = 2
c = 3
*nums, = [a, b, c]

p(nums)
```

## This breaks because

This is not valid ruby.

**Comment by reese** [comment]
Thanks for the report! The good news is that it's a super quick fix, I can get a PR up for it shortly 👍

**Comment by maxjacobson** [comment]
wow, so fast! 💨
