### ISSUE TITLE
Tree deserialization error with `and`/`or` operators

### ISSUE THREAD

**Issue by aisamanra** [samphippen/rubyfmt#447]
* Ruby version: 3.1.4
* Rubyfmt git sha: e00d2ab89fd4b0b85a7897fac393c1ad987136de

## Input file

Minimized down to:

```ruby
thing or thing.other
```

## Rubyfmt's output

```
!!! Ruby Tree Deserialization Error !!!
```

## This breaks because

This successfully parsed with v0.8, so this was a regression in v0.10.

**Comment by fables-tales** [comment]
fyi the ripper trees are the same between ruby versions, so it seems like we probably screwed up in our parse tree
