### ISSUE TITLE
`.squish` in SQL heredocs is moved to the closing SQL statement

### ISSUE THREAD

**Issue by pjg** [samphippen/rubyfmt#450]
* Ruby version: 3.1.4p223
* Rubyfmt git sha: rubyfmt-main 0.10.0 (installed via brew)

The cop: [RuboCop::Cop::Rails::SquishedSQLHeredocs](https://www.rubydoc.info/gems/rubocop-rails/2.9.1/RuboCop/Cop/Rails/SquishedSQLHeredocs)

## Input file

```ruby
<<~SQL.squish
  SELECT ...
SQL      
```

## Rubyfmt's output

```ruby
<<~SQL
  SELECT ...
SQL
  .squish
```

## This breaks because

Not exactly a "break" per se, but the `.squish` call is moved into a weird place, which results in a code, which is weirdly idented/formatted.

I am not sure if this is only (a/my) style preference or rather incorrect rubyfmt behaviour, which should be fixed. I won't be posting such issues if it's the former.

**Comment by fables-tales** [comment]
I think Rubyfmt does the right thing here
