### ISSUE TITLE
Breaks on percent strings with exotic delimiters

### ISSUE THREAD

**Issue by aergonaut** [samphippen/rubyfmt#67]
* Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
* Rubyfmt git sha: 05f7b5b0eb1a9192a034468acc99e9cbf1a00906

## Input file

```ruby
%q{}
```

```ruby
%q||
```

## Rubyfmt's output

```
/Users/chris/bin/rubyfmt:2404:in `on_string_literal': what even is this string type } (RuntimeError)
	from /Users/chris/bin/rubyfmt:2427:in `parse'
	from /Users/chris/bin/rubyfmt:2427:in `main'
	from /Users/chris/bin/rubyfmt:2444:in `<main>'
```

## This breaks because

Rubyfmt appears to expect all percent strings to use `()`. It looks like for the other percent literals, other delimiters work, so it looks like this is just a special case for percent strings.

**Comment by georgebrock** [comment]
Found another example of this problem that wasn't caught by d6c67bbe323a718cec0c7a5e8a119774281bf22e:

```ruby
%[…]
```

Real world example: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/thumbnail.rb#L106-L107

**Comment by georgebrock** [comment]
From the [Ruby 2.6 docs][1]:

> If you are using “(”, “[”, “{”, “<” you must close it with “)”, “]”, “}”, “>” respectively. You may use most other non-alphanumeric characters for percent string delimiters such as “%”, “|”, “^”, etc.

The “most other non-alphanumeric characters” bit seemed a bit vague, so I went looking for the source. The relevant bit of lexing seems to happen in [`RubyLex#identify_quotation`][2]. If I'm reading this right, we need to support:

- The pairs of characters defined in [`RubyLex::PERCENT_PAREN`][3], which are `%()`, `%[]`, `%{}`, `%<>`
- Any other character that matches `/\W/` (`%||`, `%%%`, `%^^`, …)

Ruby doesn't seem to support multibyte characters in this context. For example, despite the fact that `"☃" =~ /\W/`, this will raise: `%☃☃`.

[1]: https://docs.ruby-lang.org/en/2.6.0/syntax/literals_rdoc.html#label-Percent+Strings
[2]: https://github.com/ruby/ruby/blob/eda970cfe231797fcf19d14a8dce3a9b49880708/lib/irb/ruby-lex.rb#L925-L936
[3]: https://github.com/ruby/ruby/blob/eda970cfe231797fcf19d14a8dce3a9b49880708/lib/irb/ruby-lex.rb#L326-L331

**Comment by samphippen** [comment]
I need to overhaul the string munger to deal with this.

**Comment by samphippen** [comment]
This is "the string munger" https://github.com/samphippen/rubyfmt/blob/master/src/rubyfmt.rb#L2485

**Comment by georgebrock** [comment]
It's still kinda half-baked, but I've got the beginnings of something on the `string-improvements` branch, and specifically in 12c83eb651900c4e5e5fe4ad6d743fec291163bd

**Comment by samphippen** [comment]
closing in favour of #87
