### ISSUE TITLE
Incorrectly handles strings with escaped delimiters

### ISSUE THREAD

**Issue by georgebrock** [samphippen/rubyfmt#79]
* Ruby version:
    * ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
    * ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin18]
* Rubyfmt git sha: d7ab677db09aea627c9d8d7580fee064b66986d8

## Input file

```ruby
'\''
%(\))
%{\}}
%|\||
```

Real world example: https://github.com/thoughtbot/gitsh/blob/master/spec/units/line_editor_spec.rb#L211

## Rubyfmt's output

```ruby
"\\'"
"\\)"
"\\}"
"\\|"
```

## This breaks because

The semantics of the program have changed: the strings now contain a `\` character when previously they did not. The correct output would be:

```ruby
"'"
")"
"}"
"|"
```

There might be some additional complexity here around what needs to be escaped or unescaped, because there are cases where the closing delimiter can be used without an escape, for example balanced parens in `%()` don't need escaping, but unbalanced closing parens do:

```ruby
%((())) == "(())"
%((\))) == "())"
```

**Comment by samphippen** [comment]
I'm deceased, I guess I'm going to have to overhaul the string formatting tool.

**Comment by georgebrock** [comment]
It's still kinda half-baked, but I've got the beginnings of something on the `string-improvements` branch, and specifically in 12c83eb651900c4e5e5fe4ad6d743fec291163bd

**Comment by samphippen** [comment]
Closing in favour of #87
