### ISSUE TITLE
Incorrectly handles interpolation-like constructs in single-quoted strings

### ISSUE THREAD

**Issue by georgebrock** [samphippen/rubyfmt#81]
* Ruby version:
    - ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
    - ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin18]
* Rubyfmt git sha: 0ac338933dd3cf33c80cf5a68cbef4f39c435b26

## Input file

```ruby
'#{1}'
'#@foo'
```

## Rubyfmt's output

```
"#{1}"
"#@foo"
```

## This breaks because

The semantics of the program have changed: previously these looked like string interpolations, but weren't because of the type of quotes used; now they're in double-quotes they are interpolations.

Expected output would be escaped:

```
"\#{1}"
"\#@foo"
```

Given that this is about escaping different things based on the input string delimiters, it's probably closely related to #79

**Comment by samphippen** [comment]
Ruby is cancelled.
