### ISSUE TITLE
Lint shell files using shellcheck(1)

### ISSUE THREAD

**Issue by teoljungberg** [samphippen/rubyfmt#88]
I noticed that the shell files that is leveraged by the test tooling done by `make` aren't shellcheck compatible. I'd gladly do the work to convert the `.sh` files into a compatible state and add a proposed `make lint` command that would run on CI.

Would that be anything of value this early in the projects state?

**Comment by samphippen** [comment]
I'd support adding this as a linting pass if it goes in our dockerfiles without too much difficulty

**Comment by samphippen** [comment]
@teoljungberg do you want to have a go at updating the various CI dockerfiles to include this?

**Comment by teoljungberg** [comment]
@samphippen - sure. Would you prefer having it baked in or having a dedicated "linting" image that's run as a prior step?

**Comment by samphippen** [comment]
@teoljungberg let's throw it in all 3 of the containers for now.

**Comment by samphippen** [comment]
This is merged! Yay
