### ISSUE TITLE
More visible CI

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#92]
I think I accidentally introduced a bug with https://github.com/samphippen/rubyfmt/pull/90 – test.sh breaks on fixtures/double_splat_def_actual.rb for Ruby 2.4 and below.

It would be nice to see CI status when opening a pull request. From GitHub Actions documentation it looks like only people with write and admin rights can see Workflows on a repository.

Would you be open to use another CI than GitHub Actions?

And perhaps run the tests with Ruby 2.4 and 2.6 as well?

**Comment by bquorning** [comment]
In case you’re interested, I wrote a config file for CircleCI in this branch: https://github.com/samphippen/rubyfmt/compare/master...bquorning:circleci ([example build](https://circleci.com/workflow-run/4b556451-6e47-4719-9e43-b842805d3675))

**Comment by samphippen** [comment]
@bquorning instead of changing CI, I'm chasing the GitHub actions team to see if we can get this fixed up. Thanks for this though!

**Comment by bquorning** [comment]
Sounds good, thanks for following up.

**Comment by bquorning** [comment]
It looks like you were successful – I can see PR checks at e.g. https://github.com/samphippen/rubyfmt/pull/112/checks now ❤️
