### ISSUE TITLE
Fails against TRICK source code

### ISSUE THREAD

**Issue by mame** [samphippen/rubyfmt#98]
* Ruby version: 2.6.0
* Rubyfmt git sha: `e12b794`

## Input file

* https://github.com/tric/trick2018/blob/master/01-kinaba/entry.rb
* https://github.com/tric/trick2018/blob/master/02-mame/entry.rb
* https://github.com/tric/trick2018/blob/master/05-tompng/entry.rb
* https://github.com/tric/trick2018/blob/master/07-colin/entry.rb
* https://github.com/tric/trick2018/blob/master/08-tompng/entry.rb

## Rubyfmt's output

For example, run against 01-kinaba/entry.rb:

```
$ ruby /tmp/rubyfmt.rb entry.rb 
Traceback (most recent call last):
	18: from /tmp/rubyfmt.rb:2557:in `<main>'
	17: from /tmp/rubyfmt.rb:2554:in `main'
	16: from /tmp/rubyfmt.rb:2397:in `format_program'
	15: from /tmp/rubyfmt.rb:2397:in `each'
	14: from /tmp/rubyfmt.rb:2398:in `block in format_program'
	13: from /tmp/rubyfmt.rb:2391:in `format_expression'
	12: from /tmp/rubyfmt.rb:2323:in `block in <main>'
	11: from /tmp/rubyfmt.rb:1370:in `format_unless_mod'
	10: from /tmp/rubyfmt.rb:1378:in `format_conditional_mod'
	 9: from /tmp/rubyfmt.rb:2391:in `format_expression'
	 8: from /tmp/rubyfmt.rb:2351:in `block in <main>'
	 7: from /tmp/rubyfmt.rb:1947:in `format_alias'
	 6: from /tmp/rubyfmt.rb:171:in `with_start_of_line'
	 5: from /tmp/rubyfmt.rb:1948:in `block in format_alias'
	 4: from /tmp/rubyfmt.rb:2391:in `format_expression'
	 3: from /tmp/rubyfmt.rb:2315:in `block in <main>'
	 2: from /tmp/rubyfmt.rb:1089:in `format_symbol_literal'
	 1: from /tmp/rubyfmt.rb:171:in `with_start_of_line'
/tmp/rubyfmt.rb:1098:in `block in format_symbol_literal': didn't get ident in right position [[:@kw, "BEGIN", [1, 9]]] (RuntimeError)
```

## Note

Thank you for the great tool.

I run rubyfmt against the winning programs in [TRICK programming contest](https://github.com/tric/trick2018), which the entry programs compete in the weirdness.  And I found that it fails with an exception against some of them above.

They are not serious cases.  I'd just like to inform you.  You can close this ticket without any modification.  Thanks.

**Comment by samphippen** [comment]
@mame I actually think exactly these stress test cases are things we should be using. I'm going to add them to the rubyfmt test suite!

Thank you 😄

**Comment by samphippen** [comment]
@mame I added the first two examples here: https://github.com/samphippen/rubyfmt/blob/master/scripts/test_trick.sh.

I'm going to extend it to all the ones that are available, but if you have the time to add some tests I'd appreciate a pull request :)

**Comment by samphippen** [comment]
@mame I determined that 07-colin is impossible with rubyfmt, because the cells are formatting sensitive.

**Comment by mame** [comment]
Yes, some of the TRICK programs are very sensitive to its format.  If rubyfmt outputs a text instead of an exception, and if the text can be reasonably parsed, it would be good enough, I think.

If I hold the next TRICK contest, I will use rubyfmt during the judgment process :-)

**Comment by samphippen** [comment]
so we got the first 6 programs working with rubyfmt, I feel like that is an achievement. Thank you for your bug report because it exposed many edge cases!

**Comment by adlugopolski** [comment]
Not sure if thats perhaps included in one of the TRICK examples, but this code fails for me: 

`puts ->(num) { num }.(1)`

**Comment by samphippen** [comment]
closing, we've done what we can here.

**Comment by twe4ked** [comment]
> I determined that 07-colin is impossible with rubyfmt, because the cells are formatting sensitive.

We should probably add a skip comment for cases like this, similar to the rustfmt one:

```rust
#[rustfmt::skip]
const OFFSETS: [(i8, i8); 8] = [
    (-1, -1), (-1, 0), (-1, 1),
    ( 0, -1),/* 0  0 */( 0, 1),
    ( 1, -1), ( 1, 0), ( 1, 1),
];
```

**Comment by samphippen** [comment]
I'm unconvinced that'd be useful. Trick is filled with pathological examples of working with ruby syntax, so probably not a problem.
